# Generated by Django 4.0.4 on 2022-06-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0002_stockhistory_delete_s1301_delete_s1303_delete_s2317_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
