# Generated by Django 4.0.5 on 2022-06-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0005_alter_picadd_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='picadd',
            name='mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
